### ISSUE TITLE
Backend: Add custom errors

### ISSUE THREAD

**Issue by SleepAPI** [SleepAPI/SleepAPI#17]
### Details

Current we just throw default error everywhere, but we should create some custom errors.
They could be added in a new file under domain called something like error.ts.

Some options are ProgrammingError and NotFoundError. 

Add some custom errors and once merged create a new feature request ticket for replacing existing errors with your new suggestions.

**Comment by AdeosunDeji** [comment]
@SleepAPI can you assign this to me?

**Comment by SleepAPI** [comment]
> @SleepAPI can you assign this to me?

Done, I marked is as In Progress in the board. Let me know if you have any questions or want to discuss suggestions.
Both here and on the Discord works fine. Welcome! 👍
