### ISSUE TITLE
Tier list: Head start on skill procs 

### ISSUE THREAD

**Issue by SleepAPI** [SleepAPI/SleepAPI#20]
### Details

We could start to introduce affect of relevant skills for production amounts. We would need to clearly warn that this is experimental data, as skill% values are likely off by a significant amount.

This could show us some early indicator of how the meta looks with skills in mind.

Investigate which skills would affect produced ingredients, like:
* energizing cheer
* self charge
* energy for everyone
* ingredient magnet S

Investigate if we can have energy skills affect the whole team in the set-cover algorithm somehow too. 

This is just for backend calculation, for adding different skill-affected versions and warnings etc to the frontend we should create a follow-up ticket.

**Comment by abunzu-lj** [comment]
And metronome 😒

**Comment by SleepAPI** [comment]
> And metronome 😒 
> 

And extra helpful
