### ISSUE TITLE
Tool for listing best producers of a given ingredient

### ISSUE THREAD

**Issue by SleepAPI** [SleepAPI/SleepAPI#205]
### Details

This is basically the team finder tool, but for ingredients instead of recipes

**Comment by 3geek14** [comment]
The API route is working for this. A page to use it on the site would still be nice.

**Comment by SleepAPI** [comment]
> The API route is working for this. A page to use it on the site would still be nice.

Perhaps it could be within the same tool as team finder tool on the new site. Give it a new name, something solver?

**Comment by SleepAPI** [comment]
Closing this as it will be part of new team finder tool on site #400
