### ISSUE TITLE
Wrong inventory size for Blastoise

### ISSUE THREAD

**Issue by IstrajI** [SleepAPI/SleepAPI#208]
### Environment

Production (https://sleepapi.net/)

### Steps to Reproduce

Hello!
According to site Blastoise has inventory with size 27, but actually it's 22
![image](https://github.com/SleepAPI/SleepAPI/assets/9091709/899585bc-99e5-4eb1-b9b3-cad73deaaf11)
![image](https://github.com/SleepAPI/SleepAPI/assets/9091709/7e334f6e-a53b-4aad-9a4b-6a0115db9edd)

### Expected Result

Inventory 22

### Actual Result

Inventory 27

**Comment by SleepAPI** [comment]
Hello! @IstrajI! 
Thank you for raising concerns, in this case I believe Blastoise is listed correctly. 

By default Blastoise has a carry size of 17. Each time it has evolved it gets 5 extra carry size. Sleep API assumes it was evolved from a Squirtle, thus giving it 17+5+5. In your case I believe it was caught as a Wartortle instead, which would give it only one evolution, so 17+5. 

We have received requests to allow users to specify the number of evolutions themselves, we'll implement this at some point. 

Let me know if you have further questions 👍

**Comment by IstrajI** [comment]
Oh, thank you @SleepAPI for clarification! I didn't know that inventory depend on numbers of evolution. You'r right, I've evolved him from Wartortle

**Comment by SleepAPI** [comment]
> Oh, thank you @SleepAPI for clarification! I didn't know that inventory depend on numbers of evolution. You'r right, I've evolved him from Wartortle

Perfect, I'll close this then. Let me know if you have any more questions
