### ISSUE TITLE
prod calc: missing ouputs in logfile and on-site

### ISSUE THREAD

**Issue by abunzu-lj** [SleepAPI/SleepAPI#221]
### Environment

Development (https://dev.sleepapi.net/)

### Steps to Reproduce

![2024-03-21 17_55_29-Sleep API – Mozilla Firefox](https://github.com/SleepAPI/SleepAPI/assets/155227040/5271b622-df0c-4ea6-a8f7-b728635d74b8)
**red** (raikous skill) is missing in the logfiles and on-site (prodcalc & prodcalc-comaprison) 
**orange and pink** are only missing on-site (prodcalc & prodcalc-comaprison)
orange is ERB
pink is sleeptime

### Expected Result

all present

### Actual Result

not present

**Comment by SleepAPI** [comment]
Closing this, new site wont have output like this
