### ISSUE TITLE
Level 60 Unlock

### ISSUE THREAD

**Issue by 3geek14** [SleepAPI/SleepAPI#352]
### Details

With the upcoming new level cap, some adjustments can be made to the UI:
* Change default level on new site to 60
* Remove 55 as a quick option
* In the tier list, remove level 55, consider replacing with 30 as "beginning-friendly" list

**Comment by 3geek14** [comment]
This seems basically done. All that might remain is tier lists for the new site, but I think that can be a separate ticket. But I'll leave it open in case you can think of something I'm missing.

**Comment by SleepAPI** [comment]
> This seems basically done. All that might remain is tier lists for the new site, but I think that can be a separate ticket. But I'll leave it open in case you can think of something I'm missing.

No, I agree
