### ISSUE TITLE
Frontend/Backend: Allow user to specify sleep duration

### ISSUE THREAD

**Issue by 3geek14** [SleepAPI/SleepAPI#40]
### Details

Currently, all production calculations assume that the user is awake for 15.5 hours per day and asleep for 8.5 hours per day. Some people don't manage to sleep for that long, and the production calculator would be more useful to those people if they could specify how long they sleep.

**Comment by SleepAPI** [comment]
Good suggestion, I'll add it to the board. It's probably quite advanced since we would need to rewrite the energy formulas to dynamically calculate time spent in each bucket depending on input sleep. This would affect both daily energy levels, but also the frequency with which we start the night.

**Comment by abunzu-lj** [comment]
Then it would be good to also support energy recovery bonus skill along it.

**Comment by SleepAPI** [comment]
> Then it would be good to also support energy recovery bonus skill along it.
> This is the best practical fix for people like me (before i had a cleric) that dont get 8.5 every day.
> 
> Also i heard that children accounts need 11.5 hours of sleep to get 100 energy??? Seems like a lot.

Agreed on the ERB subskill. 

I'm not sure we should support child accounts, we probably won't see too many children use the site and I'm guessing child accounts 11.5 hours ends at like age 13 or something?
