### ISSUE TITLE
Backend: Add unevolved Pokémon

### ISSUE THREAD

**Issue by SleepAPI** [SleepAPI/SleepAPI#5]
### Details

For most features the unevolved Pokémon are redundant and will get optimized away by their evolved forms, but for the production calculator it would make sense to have access to all Pokémon.

We should keep the POKEDEX constant as it is currently. It is used for all current rankings.
We should instead create a new file under domain/pokemon called perhaps "unevolved-pokemon.ts". 

In this file we should add constants for all Pokémon that we do not already have in our other domain/pokemon files.
They should extend the Pokemon interface found in domain/pokemon/pokemon.ts. This file also shows where you can find the ing% and skill% data. You can check out the other domain/pokemon files like domain/pokemon/berry-pokemon.ts to see what it should look like.

We should also move Onix, Pupitar and Vigoroth out of the current files to the new unevolved one. They should remain in the POKEDEX constant though, as they are interesting for rankings.

We're not adding the Pokémon to the production calculator with this ticket yet, we're just adding the base data.

**Comment by 3geek14** [comment]
I can try to tackle this one this week.

**Comment by SleepAPI** [comment]
> I can try to tackle this one this week.

Sounds great! Let me know if you have any questions along the way

**Comment by 3geek14** [comment]
> We should keep the POKEDEX constant as it is currently. It is used for all current rankings.

Would it make sense to rename this constant, as it will no longer store a complete Pokedex? How about `OPTIMAL_POKEMON`, since the feature that puts a mon into that list is that nothing else is strictly an upgrade?

> We should instead create a new file under domain/pokemon called perhaps "unevolved-pokemon.ts".

How would you feel about renaming the existing constants to something like `OPTIMAL_XYZ_SPECIALISTS`, and adding new constants `INFERIOR_XYZ_SPECIALISTS` and `ALL_XYZ_SPECIALISTS`?

**Comment by SleepAPI** [comment]
> Would it make sense to rename this constant, as it will no longer store a complete Pokedex? How about `OPTIMAL_POKEMON`, since the feature that puts a mon into that list is that nothing else is strictly an upgrade?
That sounds like a great suggestion, yes definitely. 

> How would you feel about renaming the existing constants to something like `OPTIMAL_XYZ_SPECIALISTS`, and adding new constants `INFERIOR_XYZ_SPECIALISTS` and `ALL_XYZ_SPECIALISTS`? And then all the unevolved mons could go into their respective specialist files.
I like it, yes, sounds great. Inferior might seem a little harsh, but it's probably fine. 

Just so I'm with you, in ingredient-pokemon.ts we will have INFERIOR_INGREDIENT_SPECIALISTS, OPTIMAL_INGREDIENT_SPECIALISTS and ALL_INGREDIENT_SPECIALISTS (which is just concat the prior two) and we will have the same for skill and berry files.

Then in pokemon.ts we will rename POKEDEX to OPTIMAL_POKEMON, so that current existing optimal features can work as they do today. And then we should probably create a new constant called POKEDEX again, or ALL_POKEMON, whichever is fine. And we could use this new POKEDEX constant for /pokemon API for example: https://github.com/SleepAPI/SleepAPI/issues/27

So if we do that here we can close #27 too, this would also solve a big part of #6 and only leave adding the names to frontend. So if we're on the same page now, let me know, so I can update #6 and close #27

**Comment by 3geek14** [comment]
Yep, that's what I've got in mind!

**Comment by SleepAPI** [comment]
> Yep, that's what I've got in mind!

Excellent, great suggestions, go for it! I'll update the tickets
