### ISSUE TITLE
Frontend: add information about how to contribute to footers

### ISSUE THREAD

**Issue by SleepAPI** [SleepAPI/SleepAPI#57]
### Details

We should include a small notice saying something like "Want to contribute? Check [this](https://github.com/SleepAPI/SleepAPI) out." in our footer, linking to SleepAPI Github page.

EDIT: This is about the footers in the simplistic frontend. You can find this under backend/src/assets as a bunch of simple html files. Unfortunately the footers are duplicated currently across the html files and would all need to be updated unless you go for a refactor.

The footers currently mention our contact info on Discord like:
[Sleep API authors](https://discord.gg/w97qFff8n4) on Discord for questions

We should expand this with information on how to contribute to the project.

**Comment by praisejahuzoma** [comment]
Hi, can I work on this issue?

**Comment by SleepAPI** [comment]
> Hi, can I work on this issue?

Absolutely, I've assigned it to you and marked it as In Progress in the board.
Let me know if you have any questions 👍

**Comment by praisejahuzoma** [comment]
Okay, Thanks for the update, what I am adding to the footer is just the link to the project GitHub page

**Comment by SleepAPI** [comment]
> Okay, Thanks for the update, what I am adding to the footer is just the link to the project's GitHub page. You can correct me if I am wrong

Thanks for your follow-up question, that is correct. Just a simple text with a href to SleepAPI's Github landing page.
We want to keep the current link to contact the Sleep API authors on Discord, but we also want to add information on how to contribute. Please consider making sure these two texts don't stick together completely, they should be somewhat separated by space, or a divider or whatever you suggest.
Just so the text doesn't completely stick together like: 
`Sleep API authors on Discord for questions Want to contribute? Check this out`

If you want to keep it simple you can probably just add a pipe or something like:
[Sleep API authors](https://discord.gg/w97qFff8n4) on Discord for questions   |   Want to contribute? Check out [Sleep API on Github](https://github.com/SleepAPI/SleepAPI)

**Comment by praisejahuzoma** [comment]
Ok thanks a lot

**Comment by praisejahuzoma** [comment]
You can checkout the pull request

**Comment by SleepAPI** [comment]
> You can checkout the pull request

Thank you! Left a few comments 😃

**Comment by praisejahuzoma** [comment]
I have fixed the issues, can you take a look at it?

**Comment by SleepAPI** [comment]
> I have fixed the issues, can you take a look at it?

Two small comments, please have a look 😃
